on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup gcloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Create & Publish Container
        run: |
          gcloud auth configure-docker
          docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/${{ github.repository }}:${{ github.sha }} .
          docker push gcr.io/${{ secrets.GCP_PROJECT }}/${{ github.repository }}:${{ github.sha }}

      - name: Deploy
        container: ghcr.io/jamesward/easycloudrun
        with:
          entrypoint: deploy
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT }}
          COMMIT_SHA: ${{ github.sha }}
          IMAGE_NAME: ${{ github.repository }}
          IMAGE_VERSION: ${{ github.sha }}
          REGION: ${{ secrets.GCP_REGION }}
